# https://crystal-lang.org/

name = "crystal"
type = "language"

[platform.linux]
archs = ["x86_64"]
archive-prefix = "crystal-{version}-1"
download-file = "crystal-{version}-1-linux-x86_64-bundled.tar.gz"
exe-path = "bin/crystal"

[platform.macos]
archs = ["aarch64", "x86_64"]
archive-prefix = "crystal-{version}-1"
download-file = "crystal-{version}-1-darwin-universal.tar.gz"
exe-path = "bin/crystal"

[platform.windows]
archs = ["aarch64", "x86_64"]
download-file = "crystal-{version}-windows-{arch}-msvc-unsupported.zip"
exe-path = "crystal"

[install]
download-url = "https://github.com/crystal-lang/crystal/releases/download/{version}/{download_file}"

[install.exes]
[install.exes.crystal]
primary = true
no-shim = true

[install.exes.shards]
exe-path = "embedded/bin/shards"

[resolve]
git-url = "https://github.com/crystal-lang/crystal"

[detect]
version-files = [".crystal-version", ".tool-versions"]
